name: Simple Python Workflow
on:
  schedule:
    - cron: '0 */6 * * *'
  push:

jobs:
  query-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build Env
        uses: ./.github/actions/build_py_env
        with:
          requirements: reqs/simple-reqs.txt
      - name: Run Simple Script
        run: pipenv run python scripts/simple.py > data/python_report_$(date +"%Y-%m-%d_%H-%M").txt
      - name: Commit
        uses: ./.github/actions/commit
        with:
          message: new time report
          what: data/