name: Simple CLI Workflow
on:
  schedule:
    - cron: '*/5 * * * *'
  push:

jobs:
  get-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create new report
        run: date >> data/latest-cli-report.txt
      - name: Commit
        uses: ./.github/actions/commit
        with:
            message: new time report
            what: data/