name: Simple R Report
on:
  schedule:
    - cron: '30 * * * *'
  push:

jobs:
  get-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 3.6.1
      - name: Install packages
        run: |
          install.packages(c("ggplot2", "dplyr"))
        shell: Rscript {0}
      - name: Run Simple Script
        run: Rscript scripts/simple.R
      - name: Commit
        uses: ./.github/actions/commit
        with:
          message: new time report
          what: data/