name: Simple CLI Report
on:
  schedule:
    - cron: '*/10 * * * *'
  push:

jobs:
  get-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Create Date Report
      #   run: date > data/report-$(date +"%Y-%m-%d_%H-%M").txt
      # - name: Commit
      #   uses: ./.github/actions/commit
      #   with:
      #       message: new time report
      #       what: data/