name: Simple Python Report
on:
  schedule:
    - cron: '*/10 * * * *'
  push:

jobs:
  get-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Simple Script
        run: python scripts/simple.py > data/python_report_$(date +"%Y-%m-%d_%H-%M").txt
      - name: Commit
        uses: ./.github/actions/commit
        with:
            message: new time report
            what: data/